
### Variables
@url = http://localhost:3001

### Get random joke

GET {{url}}/api/v1/random


### Add joke

POST {{url}}/api/v1/new
Content-Type: application/json

{
  "joke": "This is a joke",
  "punchline": "This is a punchline"
} 


### Get joke by id

GET {{url}}/api/v1/joke/6615ca3912ed174d1e07c99a